@startuml

start
:Read points from database;
:Wait till speed > 10mph;
:Get Speed Limit;

if (Speed > Limit+5) then (Yes)
:Start Speed Sensitive timer;
:Timer stopped;
:Deduct 5pts for every 30s;

else (No)
:Initialize incrementer to 0;
repeat
  :Start speed senstive timer for 10s;
  repeat
  repeat while (Timer completed) is (No)
  ->Yes;
  :Add incrementer by 2;
repeat while (Speed under limit) is (yes)
->No;
:Increment points by incrementer;
endif
:Write points to database;
stop

@enduml
