@startuml

start
:Read userId from Session;
:Read points from database;
:Speed violation detected;
:Get Speed Limit;

if (Speed > Limit+5) then (Yes)
:Start Speed Sensitive timer;
:Timer stopped;
:Deduct 5pts for every 30s;

else (No)
:Read good driving multiplier;
repeat
  :Start speed sensitive timer for 60s;
  if (timer completed) then (Yes)
  :Multiplier = Multiplier * 2;
  endif
repeat while (speed under limit) is (yes)
->No;
endif
stop

@enduml
