@startuml

start
:Read points from database;
:Get Speed Limit;

if (Speed > Limit+5) then (Yes)
:Start Speed Sensitive timer;
:Timer stopped;
:Deduct 5pts for every 30s;

else (No)
:Read good driving multiplier;
repeat
  :Start speed senstive timer for 60s;
  repeat
  repeat while (Timer completed) is (No)
  ->Yes;
  :Multiplier = Multiplier * 2;
repeat while (Speed under limit) is (yes)
->No;
endif
:Write points to database;
stop

@enduml
